# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# The redcarpet markdown extension was enabled to add strikethrough on an online-only page.
# Since it isn't needed anyone, it is disabled to reduce dependencies.
# markdown: redcarpet
# redcarpet:
#  extensions: ["strikethrough"]

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: C++Now
email: admin@ciere.com
#description: > # this means to ignore newlines until "baseurl:"
#    A gathering of C++ experts and enthusiasts from around the world in beautiful Aspen, Colorado.
description_html: > # this means to ignore newlines until "description:"
    A gathering of C++ experts and enthusiasts from around the world in beautiful Aspen, Colorado.
description: > # this means to ignore newlines until "baseurl:"
    A gathering of C++ experts and enthusiasts from around the world in beautiful Aspen, Colorado.
baseurl: "" # the subpath of your site, e.g. /blog
url: "//cppnow.org"
locale: en_US
twitter_username: cppnow
github_username:  boostcon
feed:
    path: /feed/feed.xml

video_channel: "https://www.youtube.com/user/boostcon/"

permalink: /:categories/:year/:month/:title/

pagination:
    enabled: true
    per_page: 5
    permalink: '/page-:num/'
    title: ':title'
    limit: 0
    sort_field: 'date'
    sort_reverse: true
    autopages: false
    trail:
        before: 2
        after: 2

# Google services
google_analytics: UA—138136534-1

# Build settings
source: ./src
destination: ./_temp/jekyll
markdown: kramdown
# kramdown:
#     smart_quotes: ["apos", "apos", "quot", "quot"]
gems:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from

# Year Data Config
current_year: 2023
current_dates_formated: "May 7-12, 2023"
current_year_start_date: "May 7, 2023"
current_year_end_date: "May 12, 2023"
current_year_start_date_formatted: "2023-05-07"
current_year_end_date_formatted: "2023-05-12"

current_year_canceled: false
current_year_online: false
current_location: "Aspen, Colorado"
current_where: "in Aspen"

registration_time: "15:00 on Sunday, May 7th"
registration_day_of_week: "Sunday"
first_session_day_of_week: "Monday"

# Status
## For items that are three phase (not yet, yet, not any more) we use these values:
#### "will", "is", "was"
## For items that are only two phase, we use Boolean values (false and true)

## becomes true on the last day of the conference
over: false

## Note that we "flip" the conference (set the current_year, etc,) when we make the
##  first post about the new conference.

submission: "is"

last_cfs: "/announcements/2022/12/2023-CfS/"

## If we are doing lunch signups we want them in the FAQ.
doing_lunch_signups: true
lunch_signup_link: "https://docs.google.com/spreadsheets/d/1eS5uu-CY7FVLeUxtoAmQ8A_TvFTaXYU4Q4kbEIlhS4M/edit?usp=share_link"

## "will", "is", "was": becomes "was" when the hotel is full or the conference is over
hotel_registration: "is"
online_link_for_Meadows_reservation: "https://book.passkey.com/e/50398357/"


## "will", "is", "was": becomes "was" when  the conference is over
registration: "is"
refunds_are_free: true
refund_fee: "$30"
refund_deadline: "April 5th" # 30 days prior to conference start, except for 2021, due to virus

eventbrite_reg_URL: "https://cppnow2020.eventbrite.com/"
eventbrite_reg_iframe_HTML: "<iframe src=\"https://cppnow2020.eventbrite.com/?ref=eweb\" width=\"100%\" height=\"2900\" frameborder=\"0\" marginwidth=\"5\" marginheight=\"5\" scrolling=\"auto\"></iframe>"

krueger_reg_URL: "https://na.eventscloud.com/726524"
krueger_reg_iframe_HTML: "<iframe src=\"https://www.eiseverywhere.com/ereg/index.php?eventid=661200&\" width=\"100%\" height=\"2900\" frameborder=\"0\" marginwidth=\"5\" marginheight=\"5\" scrolling=\"auto\"></iframe>"

boost_bus_reg_URL: "https://na.eventscloud.com/738901"

volunteer_applications: "is"
volunteer_chair: "Kevin Carpenter"
deadline_for_volunteers: "February 20th, 2023"      # 10 weeks prior to start of conference
notification_for_volunteers: "February 27th, 2023"  # 9 weeks prior to start of conference
volunteer_form_URL: https://docs.google.com/forms/d/e/1FAIpQLScZmiPfReh0ZqvX9ydM_-uPPvCH0nrbL-qcImcdzFGIZb9aOQ/viewform

## "will", "is", "was": becomes "was" when  the conference is over
lightning_talk_submission: "will"
lightning_talk_submission_URL: "https://cppnow.ciere.io/"

schedule_online: false
sched_com_URL: "https://cppnow.digital-medium.co.uk/2023-schedule/"
## sched_com_URL: "https://cppnow2022.sched.org/"
## sched_com_embed_URL: "https://cppnow2022.sched.org/js/embed.js"

## previous_years_schedule: "[C++Now 2021 Schedule](/history/2021/schedule/)"
previous_years_schedule: "[C++Now 2022 Schedule](https://cppnow.digital-medium.co.uk/2022-schedule/)"

#### Promo Video
show_promo_video: true
promo_video_iframe: "<iframe width=\"100%\" height=\"480\" src=\"https://www.youtube.com/embed/Um2pH_fLv6o?controls=0\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>"

#### tagcloud
## Generated at https://www.wordclouds.com/
## Settings used:

##  Size: 800x600
##  Gap size: 0
##  Direction: horizontal
##  Shape: square
##  Colors:
##      Background: #ffffff
##      Color 1: #bfef94
##      Color 2: #a2e567
##      Color 3: #82cb41
##      Color 4: #66b71e
##      Color 5: #4b900d
##  Font: Open Sans

##  File: save as PNG plus image map
show_tag_cloud: false
tag_cloud_image: "/assets/img/tagcloud/wordcloud2019.png"
tag_cloud_map: "tagclouds/tagcloud.2019.html"
tag_cloud_image_height: "504"
tag_cloud_image_width: "577"

### Home Boxes - These are boxes on the front page. They are in pairs so that 0 and 1
## are on the first line, 2 and 3 are on the second, and 4 and 5 are on the third.
## Note that if only one box of the pair is shown, it is shown twice as wide.
## Each has a title, a link location, a photo source, a photo title, a description and
## a call to action.

## Box 0
B0_show: true
B0_title: "Be a Presenter"
B0_link: "/presenters/"
#B0_photo: "/assets/img/home/jackie.jpg"
#B0_photo_title: "Jackie Kay: Photo by Zoetica Ebb"
B0_photo: "/assets/img/content/Sean.giving.keynote.jpeg"
B0_photo_title: "Sean Parent, giving a keynote"
B0_description: "<p>Join the discussion! Get the most out of C++Now by joining the elite group of C++ experts that have presented a lightning talk or as part of the regular program.</p>"
B0_call: "Presenter Information"

## Box 1
B1_show: false
B1_title: "Join us"
B1_link: "/registration/"
B1_photo: "/assets/img/home/attendees.jpeg"
B1_photo_title: "Attendees: Photo by Zoetica Ebb"
B1_description: "<p>Attending C++Now and being part of the discussion on cutting edge C++ can be a life changing experience. The content presented at C++Now is unmatched at C++ events, but that isn't the best part of conference. The best part of the conference is the attendees that you'll meet and engage with for a week in the beautiful Colorado Rockies.</p>"
B1_call: "Register Now"

## Box 2
B2_show: false
B2_title: "Hotel"
B2_link: "/location/lodging/"
B2_photo: "/assets/img/home/AspenMeadowsResort.jpg"
B2_photo_title: "Aspen Meadows Resort"
B2_description: "<p>The conference hotel is the <a href=\"https://www.aspenmeadows.com/\">Aspen Meadows Resort</a>, a 40 acre resort a short walk from the conference venue overlooking the Roaring Fork River.</p> The hotel is currently accepting online reservations."
B2_call: "Reserve Now"

## Box 3
B3_show: true
B3_title: "Hotel"
B3_link: "/location/lodging/"
B3_photo: "/assets/img/home/AspenMeadowsResort.jpg"
B3_photo_title: "Aspen Meadows Resort"
B3_description: "<p>The conference hotel is the <a href=\"https://www.aspenmeadows.com/\">Aspen Meadows Resort</a>, a 40 acre resort a short walk from the conference venue overlooking the Roaring Fork River.</p>"
B3_call: "Learn More"

## Box 4
B4_show: true
B4_title: "COVID-19 Policy"
B4_link: "/about/COVID-19_policy/"
B4_photo: "/assets/img/home/COVID19.png"
B4_photo_title: ""
B4_description: "<p>We are committed to providing a safe experience for all attendees.</p>"
B4_call: "Learn More"


## Box 1
#B1_show: true
#B1_title: "Be a Presenter"
#B1_link: "/presenters/"
#B1_photo: "/assets/img/home/jackie.jpg"
#B1_photo_title: "Jackie Kay: Photo by Zoetica Ebb"
#B1_description: "<p>Join the discussion! Get the most out of C++Now by joining the elite group of C++ experts that have presented a lightning talk or as part of the regular program.</p>"
#B1_call: "Presenter Information"

## Box 2
#B2_show: false
#B2_title: "Travel Announcement"
#B2_link: "/announcements/2022/02/Travel-Update/"
#B2_photo: "/assets/img/location/ASE/ASE-welcome-bear.jpeg"
#B2_photo_title: "ASE Welcome Bear: Photo by Jon Kalb"
#B2_description: "<p>The Aspen Airport has announced that it will be closed during C++Now 2022.</p>"
#B2_call: "Read more"

## Box 3
#B3_show: false
#B3_title: "Be a Volunteer"
#B3_link: "/about/volunteer_program/"
#B3_photo: "/assets/img/home/volunteers.jpg"
#B3_photo_title: "Volunteers: Photo by Zoetica Ebb"
#B3_description: "<p>A small group of promising young C++ programmers is selected to be part of each C++Now. In exchange for helping run the conference, volunteers receive financial assistance and what may be a career changing opportunity.</p>"
#B3_call: "Apply Today"


