# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: C++Now
email: admin@ciere.com
description: > # this means to ignore newlines until "baseurl:"
    A gathering of C++ experts and enthusiasts from around the world in beautiful Aspen, Colorado.
baseurl: "" # the subpath of your site, e.g. /blog
url: "//cppnow.org"
locale: en_US
twitter_username: cppnow
github_username:  boostcon
feed: 
    path: /feed/feed.xml

permalink: /:categories/:year/:month/:title/

pagination:
    enabled: true
    per_page: 5
    permalink: '/page-:num/'
    title: ':title'
    limit: 0
    sort_field: 'date'
    sort_reverse: true
    autopages: false
    trail: 
        before: 2
        after: 2

# Build settings
source: ./src
destination: ./_temp/jekyll
markdown: kramdown
# kramdown:
#     smart_quotes: ["apos", "apos", "quot", "quot"]
gems:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from

# Year Data Config
current_year: 2019
current_year_start_date: "May 5, 2019"
current_year_end_date: "May 10, 2019"
current_year_start_date_formatted: "2019-05-05"
current_year_end_date_formatted: "2019-05-10"
registration_time: "4PM on Sunday, May 5th"
refund_fee: "$30"
refund_deadline: "April 5th" # 30 days prior to conference start
deadline_for_volunteers: "March 5th, 2019" # 8 weeks prior to start of conference
registration_day_of_week: "Sunday"
first_session_day_of_week: "Monday"
